# Generated by Django 4.2.6 on 2023-12-13 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Board_Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
    ]
