# Generated by Django 4.2.6 on 2023-12-14 09:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job_Board_Backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employer',
            name='company_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='listing_date',
            field=models.DateField(default=datetime.date(2023, 12, 14)),
        ),
    ]
